### PR TITLE
Fix twitter_user table to correctly handle not found errors for the `pinned_tweet` column Closes #23

### LINKED ISSUE #23: twitter_user returns empty for user names with underscore after first letter
**Describe the bug**
If I query the twitter_user table for a user name that has an underscore after the first letter I get an empty response. 

**Steampipe version (`steampipe -v`)**
Example: v0.16.4

**Plugin version (`steampipe plugin list`)**
Example: v0.2.0

**To reproduce**
Verify API return data with curl:

```
curl --request GET 'https://api.twitter.com/2/users/by/username/a_garfield101' --header 'Authorization: Bearer ....'

{"data":{"id":"108656083","name":"Andrew Garfield","username":"a_garfield101"}}
```

Check steampipe output

```
> .output line
> select * from twitter_user where username='a_garfield101'
>

```

Try a user with leading underscore to show in some cases it works

```
> select * from twitter_user where username='_fel1x'
-[ RECORD 1  ]---------------------------------------------------------------------------
id                | 212962007
name              | Felix Wilhelm
username          | _fel1x
created_at        | 2010-11-07T10:27:05-05:00
description       | Cloud security research at Project Zero
entities          | <null>
location          | Zürich, Switzerland
<snip>
_ctx              | {"connection_name":"twitter"}
```

**Expected behavior**
Information returned from the API about the user is displayed. 

**Additional context**

Tested on Mac Monterey 12.6 

I'm fairly new to using steampipe so maybe the problem is between the chair and keyboard.

### PR DESCRIPTION
**Pull request by misraved**
# Example query results
<details>
  <summary>Results</summary>
  
```
select * from twitter_user where username='a_garfield101'
[
 {
  "_ctx": {
   "connection_name": "twitter"
  },
  "created_at": "2010-01-26T22:26:07+05:30",
  "description": "Somewhere between art and technology. Thoughts and words are all mine. QA Engineer @elastic",
  "entities": {
   "annotations": null,
   "cashtags": null,
   "hashtags": null,
   "mentions": null,
   "urls": null
  },
  "id": "108656083",
  "location": "Maryland",
  "name": "Andrew Garfield",
  "pinned_tweet": null,
  "pinned_tweet_id": "935639732112982017",
  "profile_image_url": "https://pbs.twimg.com/profile_images/1243707147164307461/S6tMKyAq_normal.jpg",
  "protected": "false",
  "public_metrics": {
   "followers_count": 347,
   "following_count": 107,
   "listed_count": 11,
   "tweet_count": 4963
  },
  "url": "https://t.co/aY1u1517Ws",
  "username": "a_garfield101",
  "verified": false,
  "withheld": null
 }
]
```
</details>

### CODE REVIEW

File: twitter/table_twitter_user.go [hunk 1]
```diff
@@ -49,19 +50,34 @@ func listUser(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (
 		plugin.Logger(ctx).Error("twitter_user.listUser", "query_error", lookupErr, "opts", opts)
 		return nil, lookupErr
 	}
+
+	softError := []*twitter.ErrorObj{}
```
Comment (cbruno10) [inline twitter/table_twitter_user.go:54]:
```suggestion
	softErrors := []*twitter.ErrorObj{}
```

File: twitter/table_twitter_user.go [hunk 2]
```diff
@@ -49,19 +50,34 @@ func listUser(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (
...
+
 	// Soft error, e.g. 404
 	if len(result.Raw.Errors) > 0 {
-		errMsgs := []string{}
 		for _, e := range result.Raw.Errors {
 			plugin.Logger(ctx).Error("twitter_user.listUser", "query_error", e, "opts", opts)
-			errMsgs = append(errMsgs, fmt.Sprintf("%s: %s", e.Title, e.Detail))
+			
+			// Check if the Not Found Error is a result of "pinned_tweet_id" parameter, return nil
```
Comment (cbruno10) [inline twitter/table_twitter_user.go:61]: Why do we need to handle a not found error from the `pinned_tweet_id` parameter differently?

File: twitter/table_twitter_user.go [hunk 3]
```diff
@@ -49,19 +50,34 @@ func listUser(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (
...
 			if e.Title == "Not Found Error" {
```
Comment (cbruno10) [inline twitter/table_twitter_user.go:62]:
```suggestion
			if e.Title == "Not Found Error" && e.Parameter != "pinned_tweet_id" {
```

I think we can shorten this condition a bit

File: twitter/table_twitter_user.go [hunk 4]
```diff
@@ -49,19 +50,34 @@ func listUser(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (
...
+				if e.Parameter == "pinned_tweet_id" {
+					continue
+				}
 				return nil, nil
 			}
+			softError = append(softError, e)
+		}
+	}
+
+	if len(softError) > 0 {
```
Comment (cbruno10) [inline twitter/table_twitter_user.go:72]: What is a "soft error" in the context of this table/API? Also, why do we gather all "soft errors" and then iterate through them again here? Is it just to avoid handling errors with `e.Parameter == "pinned_tweet_id"`?

**Review by cbruno10 — CHANGES_REQUESTED** [review]
@misraved Please see suggestions/questions, thanks!

File: twitter/table_twitter_user.go (hunk 2 above)
Comment (misraved) [reply twitter/table_twitter_user.go:61]: @cbruno10 The issue occurs for the pinned_tweet column since the pinned_tweet_id (935639732112982017) doesn't exist. That's the reason why we need to handle the not found error differently.
